"use client";
import { useState } from "react";

const Andro = () => {

  const data = [
    {
      serial: 1,
      company:"ASDPL",
      institute: "AADHAR HOUSING",
      product: "HL",
      subProduct: "HL",
      dsa: "5979",
    },
    {
      serial: 2,
      company:"ASDPL",
      institute: "AADHAR HOUSING",
      product: "LAP",
      subProduct: "LAP",
      dsa: "5979",
    },
    {
      serial: 3,
      company:"ASDPL",
      institute: "AAVAS",
      product: "HL",
      subProduct: "HL",
      dsa: "332",
    },
    {
      serial: 4,
      company:"ASDPL",
      institute: "AAVAS",
      product: "LAP",
      subProduct: "LAP",
      dsa: "332",
    },
    {
      serial: 5,
      company:"ASDPL",
      institute: "ABHILOANS",
      product: "LAS",
      subProduct: "LAS",
      dsa: "ABOMAL0923",
    },
    {
      serial: 6,
      company:"ASDPL",
      institute: "ADITYA BIRLA CAPITAL",
      product: "MSME",
      subProduct: "BL",
      dsa: "DAUMUM01329",
    },
    {
      serial: 7,
      company:"ASDPL",
      institute: "ADITYA BIRLA CAPITAL",
      product: "LAP",
      subProduct: "LAP",
      dsa: "DAUMUM01329",
    },
    {
      serial: 8,
      company:"ASDPL",
      institute: "ADITYA BIRLA CAPITAL",
      product: "PL",
      subProduct: "PL",
      dsa: "DAUMUM01329",
    },
    {
      serial: 9,
      company:"ASDPL",
      institute: "ADITYA BIRLA CAPITAL",
      product: "TL",
      subProduct: "TL",
      dsa: "DAUMUM01329",
    },
    {
      serial: 10,
      company:"ASDPL",
      institute: "ADITYA BIRLA FINANCE",
      product: "BL",
      subProduct: "BL",
      dsa: "DAUMUM01329",
    },
    {
  serial: 11,
  company:"ASDPL",
  institute: "ADITYA BIRLA FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DALPAN00217",
},
{
  serial: 12,
  company:"ASDPL",
  institute: "ADITYA BIRLA FINANCE",
  product: "PL",
  subProduct: "PL",
  dsa: "DAUMUM01329",
},
{
  serial: 13,
  company:"ASDPL",
  institute: "ADITYA BIRLA FINANCE",
  product: "TL",
  subProduct: "TL",
  dsa: "DAUMUM01329",
},
{
  serial: 14,
  company:"ASDPL",
  institute: "ADITYA BIRLA HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "DAAIND00066",
},
{
  serial: 15,
  company:"ASDPL",
  institute: "ADITYA BIRLA HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DAAIND00066",
},
{
  serial: 16,
  company:"PSPL",
  institute: "AEON CREDIT (BANGALORE)",
  product: "PL",
  subProduct: "PL",
  dsa: "DSA00141",
},
{
  serial: 17,
  company:"PSPL",
  institute: "AEON CREDIT (DELHI)",
  product: "PL",
  subProduct: "PL",
  dsa: "DSA00140",
},
{
  serial: 18,
  company:"PSPL",
  institute: "AEON CREDIT (MUMBAI)",
  product: "PL",
  subProduct: "PL",
  dsa: "DSA00139",
},
{
  serial: 19,
  company:"ASDPL",
  institute: "AGRIM HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "41082",
},
{
  serial: 20,
  company:"ASDPL",
  institute: "AGRIM HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "41082",
},
{
  serial: 21,
  company:"ASDPL",
  institute: "AMBIT FINVEST",
  product: "BL",
  subProduct: "BL",
  dsa: "AGN0001697",
},
{
  serial: 22,
  company:"ASDPL",
  institute: "AMBIT FINVEST",
  product: "LAP",
  subProduct: "LAP",
  dsa: "AGN0001697",
},
{
  serial: 23,
  company:"ASDPL",
  institute: "ANAND RATHI",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSA/MUM-2/1487",
},
{
  serial: 24,
  company:"ASDPL",
  institute: "ARKA",
  product: "BL",
  subProduct: "BL",
  dsa: "DSA0024",
},
{
  serial: 25,
  company:"ASDPL",
  institute: "ARKA",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSA0024",
},
{
  serial: 26,
  company:"ASDPL",
  institute: "ARKA",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "DSA0024",
},
{
  serial: 27,
  company:"ASDPL",
  institute: "ART HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "3912",
},
{
  serial: 28,
  company:"PSPL",
  institute: "ARTHAN FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "C001",
},
{
  serial: 29,
  company:"ASDPL",
  institute: "ASHV FINANCE",
  product: "BL",
  subProduct: "BL",
  dsa: "MH50AND022020",
},
{
  serial: 30,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "AGRI",
  subProduct: "AGRI",
  dsa: "PRA000118",
},
{
  serial: 31,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "BL",
  subProduct: "MBL",
  dsa: "AVSL00451",
},
{
  serial: 32,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "CC",
  subProduct: "CC",
  dsa: "AVSL00451",
},
{
  serial: 33,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "CAS001338",
},
{
  serial: 34,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "HL",
  subProduct: "AFHL",
  dsa: "AVHL00305",
},
{
  serial: 35,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "HL",
  subProduct: "HL",
  dsa: "AVHL00305",
},
{
  serial: 36,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "AVSL00451",
},
{
  serial: 37,
  company:"ASDPL",
  institute: "AU SMALL",
  product: "TL/WC/OD",
  subProduct: "TL/WC/OD",
  dsa: "AVBB00957",
},
{
  serial: 38,
  company:"PSPL",
  institute: "AUXILLO Finserve Private Limited",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "AUXSCNN0961",
},
{
  serial: 39,
  company:"ASDPL",
  institute: "AVANSE",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "2025",
},
{
  serial: 40,
  company:"ASDPL",
  institute: "AVANSE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "2025",
},
{
  serial: 41,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "Car Loan",
  subProduct: "Auto Loan",
  dsa: "DSA1606MUM",
},
{
  serial: 42,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "DSA1606MUM",
},
{
  serial: 43,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "DSA9913MUM",
},
{
  serial: 44,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "DSA1606MUM",
},
{
  serial: 45,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "HL",
  subProduct: "Asha - HL",
  dsa: "ASHA3083MUMMORT",
},
{
  serial: 46,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSA1606MUM",
},
{
  serial: 47,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "DSA1606MUM",
},
{
  serial: 48,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "OD/CC/WC",
  subProduct: "B2B",
  dsa: "CMH00046",
},
{
  serial: 49,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "DSA1606MUM",
},
{
  serial: 50,
  company:"ASDPL",
  institute: "AXIS BANK",
  product: "TL",
  subProduct: "TL",
  dsa: "CMH00046",
},
{
  serial: 51,
  company:"ASDPL",
  institute: "AXIS FINANCE",
  product: "BL",
  subProduct: "BL",
  dsa: "AFLR186",
},
{
  serial: 52,
  company:"ASDPL",
  institute: "AXIS FINANCE",
  product: "HL",
  subProduct: "AFHL",
  dsa: "AFLR186",
},
{
  serial: 53,
  company:"ASDPL",
  institute: "AXIS FINANCE",
  product: "HL",
  subProduct: "HL",
  dsa: "AFLR186",
},
{
  serial: 54,
  company:"ASDPL",
  institute: "AXIS FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "AFLR186",
},
{
  serial: 55,
  company:"ASDPL",
  institute: "AXIS FINANCE",
  product: "PL",
  subProduct: "PL",
  dsa: "AFLR186",
},
{
  serial: 56,
  company:"ASDPL",
  institute: "BAJAJ FINANCE",
  product: "BL",
  subProduct: "BL",
  dsa: "19013",
},
{
  serial: 57,
  company:"ASDPL",
  institute: "BAJAJ FINANCE",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "10016973",
},
{
  serial: 58,
  company:"ASDPL",
  institute: "BAJAJ FINANCE",
  product: "LAS",
  subProduct: "LAS",
  dsa: "Direct",
},
{
  serial: 59,
  company:"ASDPL",
  institute: "BAJAJ FINANCE",
  product: "PL",
  subProduct: "PL",
  dsa: "19013",
},
{
  serial: 60,
  company:"ASDPL",
  institute: "Bajaj Finserv",
  product: "BL",
  subProduct: "BL",
  dsa: "19013",
},
{
  serial: 61,
  company:"ASDPL",
  institute: "Bajaj Finserv",
  product: "DL",
  subProduct: "DL",
  dsa: "19013",
},
{
  serial: 62,
  company:"ASDPL",
  institute: "Bajaj Finserv",
  product: "LAP",
  subProduct: "LAP",
  dsa: "19013",
},
{
  serial: 63,
  company:"ASDPL",
  institute: "Bajaj Finserv",
  product: "Sal ETB",
  subProduct: "Sal ETB",
  dsa: "19013",
},
{
  serial: 64,
  company:"ASDPL",
  institute: "Bajaj Finserv",
  product: "Sal Lite",
  subProduct: "Sal Lite",
  dsa: "19013",
},
{
  serial: 65,
  company:"ASDPL",
  institute: "Bajaj Finserv",
  product: "Secured",
  subProduct: "Secured",
  dsa: "19013",
},
{
  serial: 66,
  company:"ASDPL",
  institute: "BAJAJ HOUSING",
  product: "HL",
  subProduct: "AHFL / B2B / B2C / HL",
  dsa: "48055",
},
{
  serial: 67,
  company:"ASDPL",
  institute: "BAJAJ HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "48055",
},
{
  serial: 68,
  company:"ASDPL",
  institute: "BANDHAN BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "900179",
},
{
  serial: 69,
  company:"ASDPL",
  institute: "BANDHAN BANK",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "DSAMUM240015",
},
{
  serial: 70,
  company:"ASDPL",
  institute: "BANDHAN BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "10153",
},
{
  serial: 71,
  company:"ASDPL",
  institute: "BANDHAN BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "10153",
},
{
  serial: 72,
  company:"ASDPL",
  institute: "BANDHAN BANK",
  product: "OD/CC/WC",
  subProduct: "Overdraft",
  dsa: "10153",
},
{
  serial: 73,
  company:"ASDPL",
  institute: "BANDHAN BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "900179",
},
{
  serial: 74,
  company:"ASDPL",
  institute: "BANK OF BARODA",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "DSAMMS00011",
},
{
  serial: 75,
  company:"ASDPL",
  institute: "BANK OF BARODA",
  product: "HL",
  subProduct: "HL",
  dsa: "DSAMMS00011",
},
{
  serial: 76,
  company:"ASDPL",
  institute: "BANK OF BARODA",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSAMMS00011",
},
{
  serial: 77,
  company:"ASDPL",
  institute: "BANK OF INDIA",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "BSACORP021",
},
{
  serial: 78,
  company:"ASDPL",
  institute: "BANK OF INDIA",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "BSACORP021",
},
{
  serial: 79,
  company:"ASDPL",
  institute: "BANK OF INDIA",
  product: "HL",
  subProduct: "HL",
  dsa: "BSACORP021",
},
{
  serial: 80,
  company:"ASDPL",
  institute: "Bluebear Technologies (Propelled)",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "",
},
{
  serial: 81,
  company:"ASDPL",
  institute: "CAPITAL INDIA FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "308",
},
{
  serial: 82,
  company:"ASDPL",
  institute: "CAPITAL INDIA HOME",
  product: "HL",
  subProduct: "HL",
  dsa: "308",
},
{
  serial: 83,
  company:"ASDPL",
  institute: "CAPRI GLOBAL CAPITAL",
  product: "HL",
  subProduct: "HL",
  dsa: "355",
},
{
  serial: 84,
  company:"ASDPL",
  institute: "CAPRI GLOBAL CAPITAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "355",
},
{
  serial: 85,
  company:"ASDPL",
  institute: "CAPRI GLOBAL HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "1126",
},
{
  serial: 86,
  company:"ASDPL",
  institute: "CAPRI GLOBAL HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "1126",
},
{
  serial: 87,
  company:"ASDPL",
  institute: "CATHOLIC SYRIAN BANK (CSB BANK)",
  product: "HL",
  subProduct: "HL",
  dsa: "357",
},
{
  serial: 88,
  company:"ASDPL",
  institute: "CATHOLIC SYRIAN BANK (CSB BANK)",
  product: "LAP",
  subProduct: "LAP",
  dsa: "357",
},
{
  serial: 89,
  company:"ASDPL",
  institute: "CATHOLIC SYRIAN BANK (CSB BANK)",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "357",
},
{
  serial: 90,
  company:"PSPL",
  institute: "Cent Bank Home Finance",
  product: "HL",
  subProduct: "HL",
  dsa: "PANIND16",
},
{
  serial: 91,
  company:"ASDPL",
  institute: "CENTRAL BANK OF INDIA",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "C4726007",
},
{
  serial: 92,
  company:"ASDPL",
  institute: "CENTRAL BANK OF INDIA",
  product: "HL",
  subProduct: "HL",
  dsa: "C4726007",
},
{
  serial: 93,
  company:"ASDPL",
  institute: "CENTRAL BANK OF INDIA",
  product: "MSME",
  subProduct: "MSME",
  dsa: "C4726007",
},
{
  serial: 94,
  company:"ASDPL",
  institute: "CENTRAL BANK OF INDIA",
  product: "TL",
  subProduct: "TL",
  dsa: "C4726007",
},
{
  serial: 95,
  company:"ASDPL",
  institute: "CENTRUM HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "BOM/DSA/23-24/000018",
},
{
  serial: 96,
  company:"ASDPL",
  institute: "CENTRUM HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "BOM/DSA/23-24/000018",
},
{
  serial: 97,
  company:"ASDPL",
  institute: "CHOLA",
  product: "BL",
  subProduct: "BL",
  dsa: "9019",
},
{
  serial: 98,
  company:"ASDPL",
  institute: "CHOLA",
  product: "HL",
  subProduct: "HL",
  dsa: "9019",
},
{
  serial: 99,
  company:"ASDPL",
  institute: "CHOLA",
  product: "LAP",
  subProduct: "LAP",
  dsa: "9019",
},
{
  serial: 100,
  company:"ASDPL",
  institute: "CHOLA",
  product: "PL",
  subProduct: "PL",
  dsa: "9019",
},
{
  serial: 101,
  company:"ASDPL",
  institute: "CHOLA",
  product: "SME",
  subProduct: "SME",
  dsa: "9019",
},
{
  serial: 102,
  company:"ASDPL",
  institute: "CHOLA",
  product: "Car Loan",
  subProduct: "UCL",
  dsa: "9019",
},
{
  serial: 103,
  company:"ASDPL",
  institute: "CLIX CAPITAL SERVICES PVT LTD",
  product: "BL",
  subProduct: "BL",
  dsa: "1204",
},
{
  serial: 104,
  company:"ASDPL",
  institute: "CLIX CAPITAL SERVICES PVT LTD",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "1204",
},
{
  serial: 105,
  company:"ASDPL",
  institute: "CLIX CAPITAL SERVICES PVT LTD",
  product: "LAP",
  subProduct: "LAP",
  dsa: "1204",
},
{
  serial: 106,
  company:"ASDPL",
  institute: "DBS BANK LTD",
  product: "HL",
  subProduct: "HL",
  dsa: "INDANDRO0001",
},
{
  serial: 107,
  company:"ASDPL",
  institute: "DBS BANK LTD",
  product: "LAP",
  subProduct: "LAP",
  dsa: "INDANDRO0001",
},
{
  serial: 108,
  company:"ASDPL",
  institute: "DBS BANK LTD",
  product: "PL",
  subProduct: "PL",
  dsa: "INDANDRO0001",
},
{
  serial: 109,
  company:"ASDPL",
  institute: "DBS BANK LTD",
  product: "WC",
  subProduct: "WC",
  dsa: "INDANDRO0001",
},
{
  serial: 110,
  company:"ASDPL",
  institute: "DCB",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "MUM0090",
},
{
  serial: 111,
  company:"ASDPL",
  institute: "DCB",
  product: "HL",
  subProduct: "HL",
  dsa: "MUM0090",
},
{
  serial: 112,
  company:"ASDPL",
  institute: "DCB",
  product: "LAP",
  subProduct: "LAP",
  dsa: "MUM0090",
},
{
  serial: 113,
  company:"ASDPL",
  institute: "DCB",
  product: "TL",
  subProduct: "TL",
  dsa: "MUM0090",
},
{
  serial: 114,
  company:"ASDPL",
  institute: "DCB",
  product: "WC",
  subProduct: "WC",
  dsa: "MUM0090",
},
{
  serial: 115,
  company:"ASDPL",
  institute: "DEUTSCHE BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "MUR99",
},
{
  serial: 116,
  company:"ASDPL",
  institute: "DEUTSCHE BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "MUR99",
},
{
  serial: 117,
  company:"ASDPL",
  institute: "DEUTSCHE BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "MUR99",
},
{
  serial: 118,
  company:"ASDPL",
  institute: "DEUTSCHE BANK",
  product: "WC",
  subProduct: "TWC",
  dsa: "MUR99",
},
{
  serial: 119,
  company:"ASDPL",
  institute: "DMI",
  product: "HL",
  subProduct: "HL",
  dsa: "DSA-0276",
},
{
  serial: 120,
  company:"ASDPL",
  institute: "DMI",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSA-0276",
},
{
  serial: 121,
  company:"PSPL",
  institute: "DMI Finance Private Limited",
  product: "Large LAP",
  subProduct: "Large LAP",
  dsa: "ANDROMEDA",
},
{
  serial: 122,
  company:"PSPL",
  institute: "DMI Finance Private Limited",
  product: "Micro LAP",
  subProduct: "Micro LAP",
  dsa: "ANDROMEDA",
},
{
  serial: 123,
  company:"PSPL",
  institute: "DMI Finance Private Limited",
  product: "Small LAP",
  subProduct: "Small LAP",
  dsa: "ANDROMEDA",
},
{
  serial: 124,
  company:"PSPL",
  institute: "DMI Finance Private Limited",
  product: "UBL",
  subProduct: "UBL",
  dsa: "ANDROMEDA",
},
{
  serial: 125,
  company:"ASDPL",
  institute: "EASY HOME",
  product: "HL",
  subProduct: "HL",
  dsa: "EHFL/DSA/00539",
},
{
  serial: 126,
  company:"ASDPL",
  institute: "EASY HOME",
  product: "LAP",
  subProduct: "LAP",
  dsa: "EHFL/DSA/00539",
},
{
  serial: 127,
  company:"ASDPL",
  institute: "EDELWEISS HOUSING FINANCE",
  product: "HL",
  subProduct: "HL",
  dsa: "ANDROMEDA",
},
{
  serial: 128,
  company:"ASDPL",
  institute: "EDELWEISS HOUSING FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "ANDROMEDA",
},
{
  serial: 129,
  company:"ASDPL",
  institute: "EDELWEISS RETAIL FINANCE",
  product: "BL",
  subProduct: "BL",
  dsa: "15",
},
{
  serial: 130,
  company:"ASDPL",
  institute: "EDELWEISS RETAIL FINANCE LTD",
  product: "BL",
  subProduct: "SME UNSECURED",
  dsa: "15",
},
{
  serial: 131,
  company:"ASDPL",
  institute: "EDELWEISS RETAIL FINANCE LTD",
  product: "EL",
  subProduct: "Equipment Financing",
  dsa: "15",
},
{
  serial: 132,
  company:"ASDPL",
  institute: "EDELWEISS RETAIL FINANCE LTD",
  product: "LAP",
  subProduct: "SME SECURED",
  dsa: "15",
},
{
  serial: 133,
  company:"ASDPL",
  institute: "EPIMONEY (FLEXILOAN)",
  product: "BL",
  subProduct: "BL",
  dsa: "63FCDOF272709",
},
{
  serial: 134,
  company:"PSPL",
  institute: "ESAF Small Finance Bank",
  product: "HL",
  subProduct: "HL",
  dsa: "DSAMTG0032",
},
{
  serial: 135,
  company:"PSPL",
  institute: "ESAF Small Finance Bank",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSAMTG0032",
},
{
  serial: 136,
  company:"ASDPL",
  institute: "FEDBANK FINANCIAL SERVICES LIMITED",
  product: "BL",
  subProduct: "BL",
  dsa: "1013161",
},
{
  serial: 137,
  company:"ASDPL",
  institute: "FEDBANK FINANCIAL SERVICES LIMITED",
  product: "HL",
  subProduct: "HL",
  dsa: "1013161",
},
{
  serial: 138,
  company:"ASDPL",
  institute: "FEDBANK FINANCIAL SERVICES LIMITED",
  product: "LAP",
  subProduct: "LAP",
  dsa: "1013161",
},
{
  serial: 139,
  company:"ASDPL",
  institute: "FEDERAL BANK",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "2711",
},
{
  serial: 140,
  company:"ASDPL",
  institute: "FEDERAL BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "2711",
},
{
  serial: 141,
  company:"ASDPL",
  institute: "FEDERAL BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "2711",
},
{
  serial: 142,
  company:"ASDPL",
  institute: "FEDERAL BANK",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "2711",
},
{
  serial: 143,
  company:"ASDPL",
  institute: "FINNABLE",
  product: "PL",
  subProduct: "PL",
  dsa: "NA",
},
{
  serial: 144,
  company:"ASDPL",
  institute: "FINTREE",
  product: "BL",
  subProduct: "BL",
  dsa: "NA",
},
{
  serial: 145,
  company:"ASDPL",
  institute: "GIC HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "NVM/ASD/58",
},
{
  serial: 146,
  company:"ASDPL",
  institute: "GIC HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "NVM/ASD/58",
},
{
  serial: 147,
  company:"ASDPL",
  institute: "GODREJ CAPITAL",
  product: "BL",
  subProduct: "BL",
  dsa: "DSNATBOM000179",
},
{
  serial: 148,
  company:"ASDPL",
  institute: "GODREJ CAPITAL",
  product: "BL",
  subProduct: "BL-Aarohi",
  dsa: "DSNATBOM000179",
},
{
  serial: 149,
  company:"ASDPL",
  institute: "GODREJ CAPITAL",
  product: "HL",
  subProduct: "HL",
  dsa: "DSNATBOM000179",
},
{
  serial: 150,
  company:"ASDPL",
  institute: "GODREJ CAPITAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSNATBOM000179",
},
{
  serial: 151,
  company:"ASDPL",
  institute: "GODREJ HOUSING FINANCE",
  product: "HL",
  subProduct: "HL / AHL",
  dsa: "DSNATBOM000179",
},
{
  serial: 152,
  company:"ASDPL",
  institute: "GODREJ HOUSING FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSNATBOM000179",
},
{
  serial: 153,
  company:"PSPL",
  institute: "GOSREE FINANCE LTD",
  product: "BL",
  subProduct: "Micro Unsecured",
  dsa: "14 A",
},
{
  serial: 154,
  company:"PSPL",
  institute: "GOSREE FINANCE LTD",
  product: "LAP",
  subProduct: "Micro LAP",
  dsa: "14 B",
},
{
  serial: 155,
  company:"PSPL",
  institute: "GOSREE FINANCE LTD",
  product: "MSME",
  subProduct: "Micro Unsecured",
  dsa: "15a",
},
{
  serial: 156,
  company:"PSPL",
  institute: "GOSREE FINANCE LTD",
  product: "MSME-LAP",
  subProduct: "Micro LAP",
  dsa: "15b",
},
{
  serial: 157,
  company:"PSPL",
  institute: "Grihum Housing",
  product: "HL",
  subProduct: "HL",
  dsa: "001213",
},
{
  serial: 158,
  company:"PSPL",
  institute: "Grihum Housing",
  product: "LAP",
  subProduct: "LAP",
  dsa: "001213",
},
{
  serial: 159,
  company:"ASDPL",
  institute: "GROWTH SOURCE",
  product: "BL",
  subProduct: "BL",
  dsa: "TSAGSIND000271",
},
{
  serial: 160,
  company:"ASDPL",
  institute: "GROWTH SOURCE",
  product: "ML",
  subProduct: "EDI(ML)",
  dsa: "TSAGSIND000271",
},
{
  serial: 161,
  company:"ASDPL",
  institute: "GROWTH SOURCE",
  product: "PRIME LAP",
  subProduct: "PRIME LAP",
  dsa: "TSAGSIND000271",
},
{
  serial: 162,
  company:"ASDPL",
  institute: "GROWTH SOURCE",
  product: "PRO LAP",
  subProduct: "PRO LAP",
  dsa: "TSAGSIND000271",
},
{
  serial: 163,
  company:"ASDPL",
  institute: "HDB",
  product: "BL",
  subProduct: "BL",
  dsa: "ANDROMEDA",
},
{
  serial: 164,
  company:"ASDPL",
  institute: "HDB",
  product: "LAP",
  subProduct: "LAP",
  dsa: "ANDROMEDA",
},
{
  serial: 165,
  company:"ASDPL",
  institute: "HDB",
  product: "PL",
  subProduct: "PL",
  dsa: "ANDROMEDA",
},
{
  serial: 166,
  company:"ASDPL",
  institute: "HDFC BANK",
  product: "Car Loan",
  subProduct: "Auto Loan",
  dsa: "396921",
},
{
  serial: 167,
  company:"ASDPL",
  institute: "HDFC BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "396921",
},
{
  serial: 168,
  company:"ASDPL",
  institute: "HDFC BANK",
  product: "GL",
  subProduct: "GL",
  dsa: "396921",
},
{
  serial: 169,
  company:"ASDPL",
  institute: "HDFC BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "396921",
},
{
  serial: 170,
  company:"ASDPL",
  institute: "HDFC BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "396921",
},
{
  serial: 171,
  company:"ASDPL",
  institute: "HDFC BANK",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "396921",
},
{
  serial: 172,
  company:"ASDPL",
  institute: "HDFC BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "396921",
},
{
  serial: 173,
  company:"ASDPL",
  institute: "HDFC CREDILA",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "E2202050001",
},
{
  serial: 174,
  company:"ASDPL",
  institute: "HERO FINCORP",
  product: "BL",
  subProduct: "BL",
  dsa: "DEL074",
},
{
  serial: 175,
  company:"ASDPL",
  institute: "HERO FINCORP",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DEL074",
},
{
  serial: 176,
  company:"ASDPL",
  institute: "HERO FINCORP",
  product: "PL",
  subProduct: "PL",
  dsa: "OMPL00186",
},
{
  serial: 177,
  company:"ASDPL",
  institute: "HERO FINCORP",
  product: "UBL",
  subProduct: "UBL",
  dsa: "DEL074",
},
{
  serial: 178,
  company:"ASDPL",
  institute: "HERO HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "Andromeda",
},
{
  serial: 179,
  company:"ASDPL",
  institute: "HERO HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "Andromeda",
},
{
  serial: 180,
  company:"ASDPL",
  institute: "HINDUJA HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "254242",
},
{
  serial: 181,
  company:"ASDPL",
  institute: "HINDUJA HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "254242",
},
{
  serial: 182,
  company:"ASDPL",
  institute: "HINDUJA LEYLAND",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "254242",
},
{
  serial: 183,
  company:"PSPL",
  institute: "HINDUJA LEYLAND",
  product: "LAP",
  subProduct: "LAP",
  dsa: "33977",
},
{
  serial: 184,
  company:"ASDPL",
  institute: "HOMEVILLE CONSULTING",
  product: "HL",
  subProduct: "HL",
  dsa: "MUMAN135",
},
{
  serial: 185,
  company:"ASDPL",
  institute: "HSBC",
  product: "HL",
  subProduct: "HL",
  dsa: "Andro",
},
{
  serial: 186,
  company:"ASDPL",
  institute: "HSBC",
  product: "LAP",
  subProduct: "LAP",
  dsa: "Andro",
},
{
  serial: 187,
  company:"ASDPL",
  institute: "HSBC",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "Andro",
},
{
  serial: 188,
  company:"ASDPL",
  institute: "HSBC",
  product: "TL",
  subProduct: "TL",
  dsa: "Andro",
},
{
  serial: 189,
  company:"ASDPL",
  institute: "HSBC",
  product: "WC",
  subProduct: "WC",
  dsa: "Andro",
},
{
  serial: 190,
  company:"ASDPL",
  institute: "ICICI BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "296855",
},
{
  serial: 191,
  company:"ASDPL",
  institute: "ICICI BANK",
  product: "BLG-OD",
  subProduct: "BLG-OD",
  dsa: "214094",
},
{
  serial: 192,
  company:"ASDPL",
  institute: "ICICI BANK",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "EL296855",
},
{
  serial: 193,
  company:"ASDPL",
  institute: "ICICI BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "Location Wise",
},
{
  serial: 194,
  company:"ASDPL",
  institute: "ICICI BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "Location Wise",
},
{
  serial: 195,
  company:"ASDPL",
  institute: "ICICI BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "296855",
},
{
  serial: 196,
  company:"ASDPL",
  institute: "ICICI BANK",
  product: "WC",
  subProduct: "WC",
  dsa: "141995",
},
{
  serial: 197,
  company:"ASDPL",
  institute: "ICICI BANK LTD",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "296855",
},
{
  serial: 198,
  company:"ASDPL",
  institute: "ICICI HOME",
  product: "HL",
  subProduct: "HL",
  dsa: "247174",
},
{
  serial: 199,
  company:"ASDPL",
  institute: "ICICI HOME",
  product: "LAP",
  subProduct: "LAP",
  dsa: "247174",
},
{
  serial: 200,
  company:"ASDPL",
  institute: "IDBI",
  product: "HL",
  subProduct: "HL",
  dsa: "CDSAANDRO",
},
{
  serial: 201,
  company:"ASDPL",
  institute: "IDBI",
  product: "LAP",
  subProduct: "LAP",
  dsa: "CDSAANDRO",
},
{
  serial: 202,
  company:"ASDPL",
  institute: "IDFC",
  product: "BL",
  subProduct: "BL",
  dsa: "12627",
},
{
  serial: 203,
  company:"ASDPL",
  institute: "IDFC",
  product: "Car Loan",
  subProduct: "Car Loan/AL",
  dsa: "12627",
},
{
  serial: 204,
  company:"ASDPL",
  institute: "IDFC",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "12999",
},
{
  serial: 205,
  company:"ASDPL",
  institute: "IDFC",
  product: "HL",
  subProduct: "HL",
  dsa: "12627",
},
{
  serial: 206,
  company:"ASDPL",
  institute: "IDFC",
  product: "LAP",
  subProduct: "LAP",
  dsa: "12627",
},
{
  serial: 207,
  company:"ASDPL",
  institute: "IDFC",
  product: "ML",
  subProduct: "ML",
  dsa: "12627",
},
{
  serial: 208,
  company:"ASDPL",
  institute: "IDFC",
  product: "PL",
  subProduct: "PL",
  dsa: "12627",
},
{
  serial: 209,
  company:"ASDPL",
  institute: "IDFC",
  product: "STLAP",
  subProduct: "STLAP",
  dsa: "12627",
},
{
  serial: 210,
  company:"ASDPL",
  institute: "IKF FINANCE",
  product: "MSME",
  subProduct: "MSME",
  dsa: "10583",
},
{
  serial: 211,
  company:"ASDPL",
  institute: "INCRED",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "9525822448151052P",
},
{
  serial: 212,
  company:"ASDPL",
  institute: "INCRED",
  product: "LAP",
  subProduct: "LAP",
  dsa: "ANDROMEDA",
},
{
  serial: 213,
  company:"ASDPL",
  institute: "INCRED",
  product: "PL",
  subProduct: "PL",
  dsa: "ANDROMEDA",
},
{
  serial: 214,
  company:"ASDPL",
  institute: "INDIA INFOLINE",
  product: "BL",
  subProduct: "BL",
  dsa: "Online",
},
{
  serial: 215,
  company:"ASDPL",
  institute: "INDIA INFOLINE",
  product: "HL",
  subProduct: "HL",
  dsa: "405131",
},
{
  serial: 216,
  company:"ASDPL",
  institute: "INDIA INFOLINE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "405131",
},
{
  serial: 217,
  company:"ASDPL",
  institute: "INDIA INFOLINE",
  product: "PL",
  subProduct: "PL",
  dsa: "Online",
},
{
  serial: 218,
  company:"ASDPL",
  institute: "INDIA INFOLINE",
  product: "SBL",
  subProduct: "SBL",
  dsa: "405131",
},
{
  serial: 219,
  company:"PSPL",
  institute: "INDIABULLS",
  product: "HL",
  subProduct: "HL",
  dsa: "DSHPSF",
},
{
  serial: 220,
  company:"PSPL",
  institute: "INDIABULLS",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSHPSF",
},
{
  serial: 221,
  company:"ASDPL",
  institute: "INDIAN BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "COZ177112343",
},
{
  serial: 222,
  company:"ASDPL",
  institute: "INDIFI",
  product: "BL",
  subProduct: "BL",
  dsa: "",
},
{
  serial: 223,
  company:"ASDPL",
  institute: "INDOSTAR",
  product: "HL",
  subProduct: "HL",
  dsa: "3179",
},
{
  serial: 224,
  company:"ASDPL",
  institute: "INDOSTAR",
  product: "LAP",
  subProduct: "LAP",
  dsa: "3179",
},
{
  serial: 225,
  company:"ASDPL",
  institute: "INDUSIND",
  product: "BL",
  subProduct: "BL",
  dsa: "BEN224751",
},
{
  serial: 226,
  company:"ASDPL",
  institute: "INDUSIND",
  product: "CC",
  subProduct: "CC",
  dsa: "BEN224751",
},
{
  serial: 227,
  company:"ASDPL",
  institute: "INDUSIND",
  product: "HL",
  subProduct: "HL",
  dsa: "IBLV2157 / BEN224751",
},
{
  serial: 228,
  company:"ASDPL",
  institute: "INDUSIND",
  product: "LAP",
  subProduct: "LAP",
  dsa: "BEN224751",
},
{
  serial: 229,
  company:"ASDPL",
  institute: "INDUSIND",
  product: "PL",
  subProduct: "PL",
  dsa: "Location Wise",
},
{
  serial: 230,
  company:"ASDPL",
  institute: "INDUSIND",
  product: "TL",
  subProduct: "TL",
  dsa: "BEN224751",
},
{
  serial: 231,
  company:"ASDPL",
  institute: "ITI Finance",
  product: "Car Loan",
  subProduct: "AL",
  dsa: "",
},
{
  serial: 232,
  company:"ASDPL",
  institute: "JANA SMALL",
  product: "HL",
  subProduct: "Micro HL",
  dsa: "103054",
},
{
  serial: 233,
  company:"ASDPL",
  institute: "JANA SMALL",
  product: "LAP",
  subProduct: "Micro LAP",
  dsa: "103054",
},
{
  serial: 234,
  company:"PSPL",
  institute: "Jio Finance (Jio Credit)",
  product: "HL",
  subProduct: "HL",
  dsa: "900000723",
},
{
  serial: 235,
  company:"PSPL",
  institute: "Jio Finance (Jio Credit)",
  product: "LAP",
  subProduct: "LAP",
  dsa: "900000723",
},
{
  serial: 236,
  company:"ASDPL",
  institute: "JM FINANCIAL",
  product: "HL",
  subProduct: "HL",
  dsa: "HOODSA0001",
},
{
  serial: 237,
  company:"ASDPL",
  institute: "JM FINANCIAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "HOODSA0001",
},
{
  serial: 238,
  company:"PSPL",
  institute: "KARNATAKA BANK",
  product: "Car Loan",
  subProduct: "Auto Loan",
  dsa: "DSA000001626",
},
{
  serial: 239,
  company:"PSPL",
  institute: "KARNATAKA BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "DSA000001626",
},
{
  serial: 240,
  company:"PSPL",
  institute: "KARNATAKA BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSA000001626",
},
{
  serial: 241,
  company:"ASDPL",
  institute: "KARUR VYSYA",
  product: "BL",
  subProduct: "BL",
  dsa: "DMAMU00011",
},
{
  serial: 242,
  company:"ASDPL",
  institute: "KARUR VYSYA",
  product: "HL",
  subProduct: "HL",
  dsa: "DMAMU00011",
},
{
  serial: 243,
  company:"ASDPL",
  institute: "KARUR VYSYA",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DMAMU00011",
},
{
  serial: 244,
  company:"ASDPL",
  institute: "KARUR VYSYA",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "DMAMU00011",
},
{
  serial: 245,
  company:"ASDPL",
  institute: "KISETSU SAISON",
  product: "BL",
  subProduct: "BL",
  dsa: "BLPIAS062",
},
{
  serial: 246,
  company:"ASDPL",
  institute: "KISETSU SAISON",
  product: "LAP",
  subProduct: "LAP",
  dsa: "BLPIAS063",
},
{
  serial: 247,
  company:"ASDPL",
  institute: "KISETSU SAISON",
  product: "PL",
  subProduct: "PL",
  dsa: "PLPIAS062",
},
{
  serial: 248,
  company:"ASDPL",
  institute: "KISETSU SAISON",
  product: "SBL",
  subProduct: "SBL",
  dsa: "SBPIAS062",
},
{
  serial: 249,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "AGRI",
  subProduct: "AGRI",
  dsa: "449735",
},
{
  serial: 250,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "46660074",
},
{
  serial: 251,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "46660074",
},
{
  serial: 252,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "46660074",
},
{
  serial: 253,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "MSME",
  subProduct: "MSME",
  dsa: "46660074",
},
{
  serial: 254,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "ACQ082",
},
{
  serial: 255,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "46660074",
},
{
  serial: 256,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "TL",
  subProduct: "TL / CGTMSE TL / FCTL",
  dsa: "46660074",
},
{
  serial: 257,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "Vishwas-AHL",
  subProduct: "Vishwas-AHL",
  dsa: "46660074",
},
{
  serial: 258,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA BANK",
  product: "Vishwas-VLAP",
  subProduct: "Vishwas-VLAP",
  dsa: "46660074",
},
{
  serial: 259,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA PRIME LTD",
  product: "Car Loan",
  subProduct: "CL / AL",
  dsa: "ANDROMEDA",
},
{
  serial: 260,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA PRIME LTD",
  product: "LAP",
  subProduct: "LAP",
  dsa: "36978315",
},
{
  serial: 261,
  company:"ASDPL",
  institute: "KOTAK MAHINDRA PRIME LTD",
  product: "WC",
  subProduct: "WC",
  dsa: "36978315",
},
{
  serial: 262,
  company:"ASDPL",
  institute: "KRAZYBEE",
  product: "BL",
  subProduct: "BL",
  dsa: "20301000905",
},
{
  serial: 263,
  company:"ASDPL",
  institute: "KRAZYBEE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "20301000905",
},
{
  serial: 264,
  company:"ASDPL",
  institute: "KREDITBEE",
  product: "BL",
  subProduct: "BL",
  dsa: "",
},
{
  serial: 265,
  company:"ASDPL",
  institute: "KREDITBEE",
  product: "PL",
  subProduct: "PL",
  dsa: "",
},
{
  serial: 266,
  company:"ASDPL",
  institute: "L&T HOUSING FINANCE LTD",
  product: "BL",
  subProduct: "BL",
  dsa: "DSA00352",
},
{
  serial: 267,
  company:"ASDPL",
  institute: "L&T HOUSING FINANCE LTD",
  product: "HL",
  subProduct: "HL",
  dsa: "DSA00352",
},
{
  serial: 268,
  company:"ASDPL",
  institute: "L&T HOUSING FINANCE LTD",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSA00352",
},
{
  serial: 269,
  company:"ASDPL",
  institute: "L&T HOUSING FINANCE LTD",
  product: "PL",
  subProduct: "PL",
  dsa: "DSA00352",
},
{
  serial: 270,
  company:"ASDPL",
  institute: "L&T HOUSING FINANCE LTD",
  product: "SME",
  subProduct: "UBL",
  dsa: "SME00103",
},
{
  serial: 271,
  company:"ASDPL",
  institute: "LENDINGKART",
  product: "BL",
  subProduct: "BL",
  dsa: "DSA3536",
},
{
  serial: 272,
  company:"ASDPL",
  institute: "MAHINDRA AND MAHINDRA FINANCIAL SERVICES",
  product: "BL",
  subProduct: "BL",
  dsa: "VC10038421",
},
{
  serial: 273,
  company:"ASDPL",
  institute: "MAHINDRA AND MAHINDRA FINANCIAL SERVICES",
  product: "LAP",
  subProduct: "LAP",
  dsa: "VC10038421",
},
{
  serial: 274,
  company:"ASDPL",
  institute: "MAHINDRA RURAL HOUSING FINANCE LIMITED",
  product: "HL",
  subProduct: "HL",
  dsa: "863",
},
{
  serial: 275,
  company:"ASDPL",
  institute: "MAHINDRA RURAL HOUSING FINANCE LIMITED",
  product: "LPA",
  subProduct: "LAP",
  dsa: "863",
},
{
  serial: 276,
  company:"ASDPL",
  institute: "MANBA FINANCE LTD",
  product: "PL",
  subProduct: "PL",
  dsa: "3435",
},
{
  serial: 277,
  company:"ASDPL",
  institute: "MANGAL CREDIT",
  product: "BL",
  subProduct: "BL",
  dsa: "DSA00016",
},
{
  serial: 278,
  company:"ASDPL",
  institute: "MAS FINANCIAL",
  product: "BL",
  subProduct: "BL",
  dsa: "SA706",
},
{
  serial: 279,
  company:"ASDPL",
  institute: "MAS FINANCIAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "SA706",
},
{
  serial: 280,
  company:"ASDPL",
  institute: "MAS FINANCIAL",
  product: "PL",
  subProduct: "PL",
  dsa: "SA706",
},
{
  serial: 281,
  company:"ASDPL",
  institute: "MAS RURAL HOUSING AND MORTGAGE FINANCE LTD",
  product: "HL",
  subProduct: "HL",
  dsa: "771",
},
{
  serial: 282,
  company:"ASDPL",
  institute: "MIRAE ASSET FINANCIAL SERVICES (INDIA) PRIVATE LIMITED",
  product: "LAS",
  subProduct: "LAS",
  dsa: "A289390",
},
{
  serial: 283,
  company:"ASDPL",
  institute: "MIRAE ASSET FINANCIAL SERVICES (INDIA) PRIVATE LIMITED",
  product: "PL",
  subProduct: "PL",
  dsa: "A289390",
},
{
  serial: 284,
  company:"PSPL",
  institute: "MIZUHO Capsave Finance Private Limited",
  product: "BG",
  subProduct: "BG",
  dsa: "PROSALES",
},
{
  serial: 285,
  company:"ASDPL",
  institute: "MONEYWISE",
  product: "BL",
  subProduct: "BL",
  dsa: "MWDSA0311",
},
{
  serial: 286,
  company:"ASDPL",
  institute: "MONEYWISE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "MWDSA0311",
},
{
  serial: 287,
  company:"ASDPL",
  institute: "MOTILAL",
  product: "HL",
  subProduct: "HL",
  dsa: "DR0004",
},
{
  serial: 288,
  company:"ASDPL",
  institute: "MOTILAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DR0004",
},
{
  serial: 289,
  company:"ASDPL",
  institute: "MUTHOOT FINANCE LTD",
  product: "BL",
  subProduct: "BL",
  dsa: "Mum002",
},
{
  serial: 290,
  company:"ASDPL",
  institute: "MUTHOOT FINANCE LTD",
  product: "PL",
  subProduct: "PL",
  dsa: "PLDS7148087",
},
{
  serial: 291,
  company:"PSPL",
  institute: "MUTHOOT FINCORP",
  product: "LAP",
  subProduct: "LAP",
  dsa: "CORP0003",
},
{
  serial: 292,
  company:"ASDPL",
  institute: "MUTHOOT HOME FIN",
  product: "HL",
  subProduct: "HL",
  dsa: "CORP0003",
},
{
  serial: 293,
  company:"ASDPL",
  institute: "MUTHOOT HOME FIN",
  product: "LAP",
  subProduct: "LAP",
  dsa: "CORP0003",
},
{
  serial: 294,
  company:"ASDPL",
  institute: "MUTHOOT HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "783",
},
{
  serial: 295,
  company:"ASDPL",
  institute: "MUTHOOT HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "783",
},
{
  serial: 296,
  company:"ASDPL",
  institute: "MUTHOOT HOUSING (MAHARASHTRA)",
  product: "HL / LAP",
  subProduct: "HL / LAP",
  dsa: "CCMH005",
},
{
  serial: 297,
  company:"ASDPL",
  institute: "NEOGROWTH CREDIT PVT LTD",
  product: "BL",
  subProduct: "BL",
  dsa: "5696",
},
{
  serial: 298,
  company:"ASDPL",
  institute: "NEOGROWTH CREDIT PVT LTD",
  product: "UBL",
  subProduct: "UBL",
  dsa: "5696",
},
{
  serial: 299,
  company:"ASDPL",
  institute: "NIDO HOME",
  product: "HL",
  subProduct: "HL",
  dsa: "ANDROMEDA",
},
{
  serial: 300,
  company:"ASDPL",
  institute: "NIDO HOME",
  product: "LAP",
  subProduct: "LAP",
  dsa: "ANDROMEDA",
},
{
  serial: 301,
  company:"ASDPL",
  institute: "NIWAS HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "3179",
},
{
  serial: 302,
  company:"ASDPL",
  institute: "NIWAS HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "3179",
},
{
  serial: 303,
  company:"ASDPL",
  institute: "NOMISMA-FT CASH",
  product: "BL",
  subProduct: "BL",
  dsa: "CORPFTC209",
},
{
  serial: 304,
  company:"ASDPL",
  institute: "ORIX",
  product: "LAP",
  subProduct: "LAP",
  dsa: "F/BR024609",
},
{
  serial: 305,
  company:"ASDPL",
  institute: "PAYSENSE",
  product: "PL",
  subProduct: "PL",
  dsa: "NA",
},
{
  serial: 306,
  company:"ASDPL",
  institute: "PIRAMAL",
  product: "BL",
  subProduct: "BL",
  dsa: "DAMUM00020",
},
{
  serial: 307,
  company:"ASDPL",
  institute: "PIRAMAL",
  product: "HL",
  subProduct: "HL",
  dsa: "DAMUM00020",
},
{
  serial: 308,
  company:"ASDPL",
  institute: "PIRAMAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DAMUM00020",
},
{
  serial: 309,
  company:"ASDPL",
  institute: "PIRAMAL",
  product: "PL",
  subProduct: "PL",
  dsa: "DAMUM00020",
},
{
  serial: 310,
  company:"ASDPL",
  institute: "PNB BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "HLRLC3845104",
},
{
  serial: 311,
  company:"ASDPL",
  institute: "PNB HOUSING FINANCE LTD",
  product: "HL",
  subProduct: "HL",
  dsa: "7380000094",
},
{
  serial: 312,
  company:"ASDPL",
  institute: "PNB HOUSING FINANCE LTD",
  product: "LAP",
  subProduct: "LAP",
  dsa: "7380000094",
},
{
  serial: 313,
  company:"ASDPL",
  institute: "POONAWALLA FINCORP",
  product: "BL",
  subProduct: "BL",
  dsa: "FMH01679",
},
{
  serial: 314,
  company:"ASDPL",
  institute: "POONAWALLA FINCORP",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "FMH01679",
},
{
  serial: 315,
  company:"ASDPL",
  institute: "POONAWALLA FINCORP",
  product: "LAP",
  subProduct: "LAP",
  dsa: "26458",
},
{
  serial: 316,
  company:"ASDPL",
  institute: "POONAWALLA FINCORP",
  product: "ME/ML",
  subProduct: "ME/ML",
  dsa: "FMH01679",
},
{
  serial: 317,
  company:"ASDPL",
  institute: "POONAWALLA FINCORP",
  product: "PL",
  subProduct: "PL",
  dsa: "1213",
},
{
  serial: 318,
  company:"ASDPL",
  institute: "PROFECTUS",
  product: "LAP",
  subProduct: "LAP",
  dsa: "700000320",
},
{
  serial: 319,
  company:"ASDPL",
  institute: "PROFECTUS",
  product: "ML",
  subProduct: "ML",
  dsa: "700000320",
},
{
  serial: 320,
  company:"ASDPL",
  institute: "PROTIUM (GROWTH SOURCE)",
  product: "BL",
  subProduct: "BL",
  dsa: "TSAGSIND000271",
},
{
  serial: 321,
  company:"ASDPL",
  institute: "PROTIUM (GROWTH SOURCE)",
  product: "LAP",
  subProduct: "LAP",
  dsa: "TSAGSIND000271",
},
{
  serial: 322,
  company:"ASDPL",
  institute: "PROTIUM (GROWTH SOURCE)",
  product: "MFL",
  subProduct: "MFL",
  dsa: "TSAGSIND000271",
},
{
  serial: 323,
  company:"ASDPL",
  institute: "PROTIUM (GROWTH SOURCE)",
  product: "ML",
  subProduct: "ML",
  dsa: "TSAGSIND000271",
},
{
  serial: 324,
  company:"ASDPL",
  institute: "PURPLE FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "V01388",
},
{
  serial: 325,
  company:"PSPL",
  institute: "RAMKRISHNA Pure Finance Private Limited",
  product: "LAP",
  subProduct: "LAP",
  dsa: "RKPF00425760925",
},
{
  serial: 326,
  company:"ASDPL",
  institute: "RATNAKAR BANK",
  product: "CC",
  subProduct: "CC",
  dsa: "AHLD0068",
},
{
  serial: 327,
  company:"ASDPL",
  institute: "RATNAKAR BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "AHLD0068",
},
{
  serial: 328,
  company:"ASDPL",
  institute: "RATNAKAR BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "PANAANDR",
},
{
  serial: 329,
  company:"ASDPL",
  institute: "RATNAKAR BANK",
  product: "OD / WC",
  subProduct: "WC OD",
  dsa: "PANAANDR",
},
{
  serial: 330,
  company:"PSPL",
  institute: "REPCO HOME FINANCE LIMITED",
  product: "HL",
  subProduct: "HL",
  dsa: "RHFL/BVI/CODSA/009",
},
{
  serial: 331,
  company:"PSPL",
  institute: "REPCO HOME FINANCE LIMITED",
  product: "LAP",
  subProduct: "LAP",
  dsa: "RHFL/BVI/CODSA/009",
},
{
  serial: 332,
  company:"PSPL",
  institute: "SAMMAAN CAPITAL",
  product: "HL",
  subProduct: "HL",
  dsa: "DSHPSF",
},
{
  serial: 333,
  company:"PSPL",
  institute: "SAMMAAN CAPITAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSHPSF",
},
{
  serial: 334,
  company:"PSPL",
  institute: "SAMMAAN FINSERVE",
  product: "HL",
  subProduct: "HL",
  dsa: "DSHPSF",
},
{
  serial: 335,
  company:"PSPL",
  institute: "SAMMAAN FINSERVE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSHPSF",
},
{
  serial: 336,
  company:"PSPL",
  institute: "SARASWAT BANK",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "CCBGMUMBB00011",
},
{
  serial: 337,
  company:"PSPL",
  institute: "SARASWAT BANK",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "RBG156",
},
{
  serial: 338,
  company:"PSPL",
  institute: "SARASWAT BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "CCBGMUMBB00011",
},
{
  serial: 339,
  company:"PSPL",
  institute: "SARASWAT BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "CCBGMUMBB00011",
},
{
  serial: 340,
  company:"PSPL",
  institute: "SARASWAT BANK",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "CCBGMUMBB00011",
},
{
  serial: 341,
  company:"PSPL",
  institute: "SARASWAT BANK",
  product: "TL",
  subProduct: "TL",
  dsa: "RBG156",
},
{
  serial: 342,
  company:"PSPL",
  institute: "SARASWAT BANK",
  product: "WC",
  subProduct: "WC",
  dsa: "RBG156",
},
{
  serial: 343,
  company:"PSPL",
  institute: "SATIN HOUSING",
  product: "AHL",
  subProduct: "AHL",
  dsa: "PAN/252/0225",
},
{
  serial: 344,
  company:"PSPL",
  institute: "SATIN HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "PAN/252/0225",
},
{
  serial: 345,
  company:"PSPL",
  institute: "SATIN HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "PAN/252/0225",
},
{
  serial: 346,
  company:"PSPL",
  institute: "SATIN HOUSING",
  product: "Micro HL",
  subProduct: "Micro HL",
  dsa: "PAN/252/0225",
},
{
  serial: 347,
  company:"PSPL",
  institute: "SATIN HOUSING",
  product: "Micro LAP",
  subProduct: "Micro LAP",
  dsa: "PAN/252/0225",
},
{
  serial: 348,
  company:"ASDPL",
  institute: "SBI",
  product: "HL",
  subProduct: "HL",
  dsa: "MUMHLC03196",
},
{
  serial: 349,
  company:"ASDPL",
  institute: "SBI CAP",
  product: "HL",
  subProduct: "HL",
  dsa: "MUM02015811P",
},
{
  serial: 350,
  company:"ASDPL",
  institute: "SBM BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "C000001254",
},
{
  serial: 351,
  company:"ASDPL",
  institute: "SBM BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "C000001254",
},
{
  serial: 352,
  company:"ASDPL",
  institute: "SBM BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "C000001254",
},
{
  serial: 353,
  company:"ASDPL",
  institute: "SBM BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "C000001254",
},
{
  serial: 354,
  company:"ASDPL",
  institute: "SC- CAPITAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "",
},
{
  serial: 355,
  company:"ASDPL",
  institute: "SC- CAPITAL",
  product: "LAS",
  subProduct: "LAS",
  dsa: "",
},
{
  serial: 356,
  company:"ASDPL",
  institute: "SHINHAN BANK",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "SHB2019006",
},
{
  serial: 357,
  company:"ASDPL",
  institute: "SHINHAN BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "SHB2019006",
},
{
  serial: 358,
  company:"ASDPL",
  institute: "SHINHAN BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "SHB2019006",
},
{
  serial: 359,
  company:"ASDPL",
  institute: "SHINHAN BANK",
  product: "LRD",
  subProduct: "LRD",
  dsa: "SHB2019006",
},
{
  serial: 360,
  company:"ASDPL",
  institute: "SHRIRAM FINANCE",
  product: "BL",
  subProduct: "BL",
  dsa: "ANDRO",
},
{
  serial: 361,
  company:"ASDPL",
  institute: "SHRIRAM FINANCE",
  product: "HL",
  subProduct: "HL",
  dsa: "ANDRO",
},
{
  serial: 362,
  company:"ASDPL",
  institute: "SHRIRAM FINANCE",
  product: "PL",
  subProduct: "PL",
  dsa: "ANDRO",
},
{
  serial: 363,
  company:"ASDPL",
  institute: "SHRIRAM HOUSING (TRUHOME FINANCE)",
  product: "HL",
  subProduct: "HL",
  dsa: "HMUMBASADP",
},
{
  serial: 364,
  company:"ASDPL",
  institute: "SHRIRAM HOUSING (TRUHOME FINANCE)",
  product: "LAP",
  subProduct: "LAP",
  dsa: "HMUMBASADP",
},
{
  serial: 365,
  company:"ASDPL",
  institute: "SHUBHAM HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "5920",
},
{
  serial: 366,
  company:"ASDPL",
  institute: "SHUBHAM HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "5920",
},
{
  serial: 367,
  company:"PSPL",
  institute: "Si Creva Capital Services Private Limited (Kissht)",
  product: "LAP",
  subProduct: "Micro Lap",
  dsa: "LAPCC0000CEN0002",
},
{
  serial: 368,
  company:"ASDPL",
  institute: "SINGULARITY CREDITWORLD",
  product: "AHL",
  subProduct: "AHL",
  dsa: "MUMCD173",
},
{
  serial: 369,
  company:"ASDPL",
  institute: "SINGULARITY CREDITWORLD",
  product: "ALAP",
  subProduct: "ALAP",
  dsa: "MUMCD173",
},
{
  serial: 370,
  company:"ASDPL",
  institute: "SINGULARITY CREDITWORLD",
  product: "HL",
  subProduct: "HL",
  dsa: "MUMCD173",
},
{
  serial: 371,
  company:"ASDPL",
  institute: "SINGULARITY CREDITWORLD",
  product: "LAP",
  subProduct: "LAP",
  dsa: "MUMCD173",
},
{
  serial: 372,
  company:"ASDPL",
  institute: "SMFG",
  product: "BL",
  subProduct: "BL",
  dsa: "MA022",
},
{
  serial: 373,
  company:"ASDPL",
  institute: "SMFG",
  product: "LAS",
  subProduct: "LAS",
  dsa: "MA022",
},
{
  serial: 374,
  company:"ASDPL",
  institute: "SMFG",
  product: "PL",
  subProduct: "PL",
  dsa: "MA022",
},
{
  serial: 375,
  company:"ASDPL",
  institute: "SMFG HOME",
  product: "HL",
  subProduct: "HL",
  dsa: "HMA005",
},
{
  serial: 376,
  company:"ASDPL",
  institute: "SMFG HOME",
  product: "LAP",
  subProduct: "LAP",
  dsa: "HMA005",
},
{
  serial: 377,
  company:"ASDPL",
  institute: "SOUTH INDIAN BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "ASD1009",
},
{
  serial: 378,
  company:"ASDPL",
  institute: "SOUTH INDIAN BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "ASD1009",
},
{
  serial: 379,
  company:"ASDPL",
  institute: "SOUTH INDIAN BANK",
  product: "ML",
  subProduct: "ML",
  dsa: "ASD1009",
},
{
  serial: 380,
  company:"ASDPL",
  institute: "SOUTH INDIAN BANK",
  product: "MSME",
  subProduct: "MSME",
  dsa: "ASD1009",
},
{
  serial: 381,
  company:"ASDPL",
  institute: "SOUTH INDIAN BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "ASD1009",
},
{
  serial: 382,
  company:"ASDPL",
  institute: "STANDARD CHARTERED BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "204683",
},
{
  serial: 383,
  company:"ASDPL",
  institute: "STANDARD CHARTERED BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "204683",
},
{
  serial: 384,
  company:"ASDPL",
  institute: "STANDARD CHARTERED BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "204683",
},
{
  serial: 385,
  company:"ASDPL",
  institute: "STANDARD CHARTERED BANK",
  product: "LAS",
  subProduct: "LAS",
  dsa: "SCL0448",
},
{
  serial: 386,
  company:"ASDPL",
  institute: "STANDARD CHARTERED BANK",
  product: "ME",
  subProduct: "ME",
  dsa: "204683",
},
{
  serial: 387,
  company:"ASDPL",
  institute: "STANDARD CHARTERED BANK",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "204683",
},
{
  serial: 388,
  company:"ASDPL",
  institute: "SUNDARAM",
  product: "HL",
  subProduct: "HL",
  dsa: "2048",
},
{
  serial: 389,
  company:"ASDPL",
  institute: "SUNDARAM",
  product: "LAP",
  subProduct: "LAP",
  dsa: "2048",
},
{
  serial: 390,
  company:"ASDPL",
  institute: "SURYODAY",
  product: "HL",
  subProduct: "HL",
  dsa: "V03512",
},
{
  serial: 391,
  company:"ASDPL",
  institute: "SURYODAY",
  product: "LAP",
  subProduct: "LAP",
  dsa: "V03512",
},
{
  serial: 392,
  company:"ASDPL",
  institute: "SURYODAY",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "V03512",
},
{
  serial: 393,
  company:"ASDPL",
  institute: "SVAKARMA FINANCE",
  product: "BL",
  subProduct: "BL",
  dsa: "Andromeda",
},
{
  serial: 394,
  company:"ASDPL",
  institute: "SVAKARMA FINANCE",
  product: "LAP",
  subProduct: "LAP",
  dsa: "Andromeda",
},
{
  serial: 395,
  company:"PSPL",
  institute: "SVC Bank",
  product: "AHL / Non AHL",
  subProduct: "AHL / Non AHL",
  dsa: "SVCBLGMUMPF072582",
},
{
  serial: 396,
  company:"PSPL",
  institute: "SVC Bank",
  product: "DL",
  subProduct: "DL",
  dsa: "SVCBLGMUMPF072582",
},
{
  serial: 397,
  company:"PSPL",
  institute: "SVC Bank",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "SVCBLGMUMPF072582",
},
{
  serial: 398,
  company:"PSPL",
  institute: "SVC Bank",
  product: "HL",
  subProduct: "HL",
  dsa: "SVCBLGMUMPF072582",
},
{
  serial: 399,
  company:"PSPL",
  institute: "SVC Bank",
  product: "LAP",
  subProduct: "LAP",
  dsa: "SVCBLGMUMPF072582",
},
{
  serial: 400,
  company:"PSPL",
  institute: "SVC Bank",
  product: "MSME",
  subProduct: "MSME",
  dsa: "SVCBLGMUMPF072582",
},
{
  serial: 401,
  company:"ASDPL",
  institute: "TATA CAPITAL",
  product: "BL",
  subProduct: "BL",
  dsa: "8089478",
},
{
  serial: 402,
  company:"ASDPL",
  institute: "TATA CAPITAL",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "8089478",
},
{
  serial: 403,
  company:"ASDPL",
  institute: "TATA CAPITAL",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "8089478",
},
{
  serial: 404,
  company:"ASDPL",
  institute: "TATA CAPITAL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "8089478",
},
{
  serial: 405,
  company:"ASDPL",
  institute: "TATA CAPITAL",
  product: "LAS",
  subProduct: "LAS",
  dsa: "8089478",
},
{
  serial: 406,
  company:"ASDPL",
  institute: "TATA CAPITAL",
  product: "PL",
  subProduct: "PL",
  dsa: "8089478",
},
{
  serial: 407,
  company:"ASDPL",
  institute: "TATA CAPITAL",
  product: "TL",
  subProduct: "TL",
  dsa: "8089478",
},
{
  serial: 408,
  company:"ASDPL",
  institute: "Tata Capital Ltd",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "8089478",
},
{
  serial: 409,
  company:"ASDPL",
  institute: "Tata Capital Ltd",
  product: "MBL",
  subProduct: "MBL",
  dsa: "8089478",
},
{
  serial: 410,
  company:"ASDPL",
  institute: "TATA HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "8089478",
},
{
  serial: 411,
  company:"ASDPL",
  institute: "TATA HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "8089478",
},
{
  serial: 412,
  company:"ASDPL",
  institute: "TATA HOUSING",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "8089478",
},
{
  serial: 413,
  company:"ASDPL",
  institute: "TRUCAP",
  product: "BL",
  subProduct: "BL",
  dsa: "CP-1095",
},
{
  serial: 414,
  company:"PSPL",
  institute: "TYGER CAPITAL / TYGER HOME (Adani)",
  product: "HL",
  subProduct: "HL",
  dsa: "HL0619",
},
{
  serial: 415,
  company:"PSPL",
  institute: "TYGER CAPITAL / TYGER HOME (Adani)",
  product: "MSME",
  subProduct: "MSME",
  dsa: "SCME1560",
},
{
  serial: 416,
  company:"ASDPL",
  institute: "UBI (UNION BANK OF INDIA)",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "MUM000322",
},
{
  serial: 417,
  company:"ASDPL",
  institute: "UBI (UNION BANK OF INDIA)",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "MUM000322",
},
{
  serial: 418,
  company:"ASDPL",
  institute: "UBI (UNION BANK OF INDIA)",
  product: "HL",
  subProduct: "HL",
  dsa: "MUM000322",
},
{
  serial: 419,
  company:"ASDPL",
  institute: "UBI (UNION BANK OF INDIA)",
  product: "LAP",
  subProduct: "LAP",
  dsa: "MUM000322",
},
{
  serial: 420,
  company:"ASDPL",
  institute: "UBI (UNION BANK OF INDIA) (HYDERABAD)",
  product: "HL/LAP",
  subProduct: "HL / LAP",
  dsa: "HYD000065",
},
{
  serial: 421,
  company:"ASDPL",
  institute: "UGRO",
  product: "BL",
  subProduct: "BL",
  dsa: "GP0070",
},
{
  serial: 422,
  company:"ASDPL",
  institute: "UGRO",
  product: "LAP",
  subProduct: "LAP",
  dsa: "GP0070",
},
{
  serial: 423,
  company:"ASDPL",
  institute: "UGRO",
  product: "ML",
  subProduct: "Machinery",
  dsa: "GP0070",
},
{
  serial: 424,
  company:"ASDPL",
  institute: "UGRO",
  product: "Solar Panel",
  subProduct: "Solar Panel",
  dsa: "GP0070",
},
{
  serial: 425,
  company:"ASDPL",
  institute: "UJJIVAN",
  product: "HL",
  subProduct: "HL",
  dsa: "1101C2180",
},
{
  serial: 426,
  company:"ASDPL",
  institute: "UJJIVAN",
  product: "LAP",
  subProduct: "LAP",
  dsa: "Andromeda",
},
{
  serial: 427,
  company:"ASDPL",
  institute: "UJJIVAN",
  product: "PL",
  subProduct: "PL",
  dsa: "40803",
},
{
  serial: 428,
  company:"ASDPL",
  institute: "UJJIVAN",
  product: "WC",
  subProduct: "WC",
  dsa: "Andromeda",
},
{
  serial: 429,
  company:"ASDPL",
  institute: "UNITY SMALL",
  product: "BL",
  subProduct: "BL",
  dsa: "ANDROMED",
},
{
  serial: 430,
  company:"ASDPL",
  institute: "UNITY SMALL",
  product: "EL",
  subProduct: "Social Infra",
  dsa: "ANDROMED",
},
{
  serial: 431,
  company:"ASDPL",
  institute: "UNITY SMALL",
  product: "LAP",
  subProduct: "LAP",
  dsa: "ANDROMED",
},
{
  serial: 432,
  company:"ASDPL",
  institute: "UTKARSH",
  product: "BL",
  subProduct: "BL",
  dsa: "R028R218",
},
{
  serial: 433,
  company:"ASDPL",
  institute: "UTKARSH",
  product: "HL",
  subProduct: "HL",
  dsa: "R028R218",
},
{
  serial: 434,
  company:"ASDPL",
  institute: "UTKARSH",
  product: "LAP",
  subProduct: "LAP",
  dsa: "R028R218",
},
{
  serial: 435,
  company:"ASDPL",
  institute: "UTKARSH",
  product: "PL",
  subProduct: "PL",
  dsa: "R028R218",
},
{
  serial: 436,
  company:"ASDPL",
  institute: "UTKARSH",
  product: "TL",
  subProduct: "TL",
  dsa: "R028R218",
},
{
  serial: 437,
  company:"ASDPL",
  institute: "UTKARSH",
  product: "WC",
  subProduct: "WC-BBG",
  dsa: "R028R218",
},
{
  serial: 438,
  company:"ASDPL",
  institute: "VASTU HOUSING",
  product: "HL",
  subProduct: "HL",
  dsa: "MUMD030",
},
{
  serial: 439,
  company:"ASDPL",
  institute: "VASTU HOUSING",
  product: "LAP",
  subProduct: "LAP",
  dsa: "MUMD030",
},
{
  serial: 440,
  company:"ASDPL",
  institute: "VISTAAR",
  product: "BL",
  subProduct: "BL",
  dsa: "VCP Code 9000007",
},
{
  serial: 441,
  company:"ASDPL",
  institute: "YES BANK",
  product: "Car Loan",
  subProduct: "Auto Loan",
  dsa: "DSAALNMUM28",
},
{
  serial: 442,
  company:"ASDPL",
  institute: "YES BANK",
  product: "BL",
  subProduct: "BL",
  dsa: "DSABLNNGP1",
},
{
  serial: 443,
  company:"ASDPL",
  institute: "YES BANK",
  product: "CASA",
  subProduct: "Term and CASA deposits",
  dsa: "DSAMEFMUM010",
},
{
  serial: 444,
  company:"ASDPL",
  institute: "YES BANK",
  product: "Car Loan",
  subProduct: "CL",
  dsa: "DSAALNMUM28",
},
{
  serial: 445,
  company:"ASDPL",
  institute: "YES BANK",
  product: "EL",
  subProduct: "Education Loans",
  dsa: "DSAELNMUM3",
},
{
  serial: 446,
  company:"ASDPL",
  institute: "YES BANK",
  product: "EL",
  subProduct: "Equipment Financing",
  dsa: "DSASBLMUM67",
},
{
  serial: 447,
  company:"ASDPL",
  institute: "YES BANK",
  product: "HL",
  subProduct: "HL",
  dsa: "DSAAHLMUM5",
},
{
  serial: 448,
  company:"ASDPL",
  institute: "YES BANK",
  product: "LAP",
  subProduct: "LAP",
  dsa: "DSASBLMUM67",
},
{
  serial: 449,
  company:"ASDPL",
  institute: "YES BANK",
  product: "ML",
  subProduct: "ML",
  dsa: "DSAHCFMUMBAI21",
},
{
  serial: 450,
  company:"ASDPL",
  institute: "YES BANK",
  product: "OD",
  subProduct: "Overdraft",
  dsa: "DSASBLMUM67",
},
{
  serial: 451,
  company:"ASDPL",
  institute: "YES BANK",
  product: "PL",
  subProduct: "PL",
  dsa: "DSAPLNMUM2",
},
{
  serial: 452,
  company:"ASDPL",
  institute: "YES BANK",
  product: "Car Loan",
  subProduct: "UCL",
  dsa: "DSAALNMUM28",
},
  ];

  const [currentPage, setCurrentPage] = useState(1);
  const recordsPerPage = 25;

  const lastIndex = currentPage * recordsPerPage;
  const firstIndex = lastIndex - recordsPerPage;
  const currentRecords = data.slice(firstIndex, lastIndex);

  const totalPages = Math.ceil(data.length / recordsPerPage);

const getPagination = () => {
  const pages = [];

  if (totalPages <= 6) {
    for (let i = 1; i <= totalPages; i++) pages.push(i);
  } else {
    pages.push(1, 2);

    if (currentPage > 4) pages.push("...");

    const start = Math.max(3, currentPage - 1);
    const end = Math.min(totalPages - 2, currentPage + 1);

    for (let i = start; i <= end; i++) {
      pages.push(i);
    }

    if (currentPage < totalPages - 3) pages.push("...");

    pages.push(totalPages - 1, totalPages);
  }

  return pages;
};

  const nextPage = () => {
    if(currentPage < totalPages){
      setCurrentPage(currentPage + 1);
    }
  };

  const prevPage = () => {
    if(currentPage > 1){
      setCurrentPage(currentPage - 1);
    }
  };

  return (

    <div className="max-w-7xl mx-auto p-3 sm:p-4 md:p-6">

      {/* Header */}

      <div className="mb-8">

        <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold mb-4 bg-gradient-to-r from-purple-700 via-pink-600 to-indigo-600 bg-clip-text text-transparent">
          Andromeda Codes For Respective Banks.
        </h1>

        <p className="text-gray-600 dark:text-gray-300 mt-2">
          Complete list of banks and NBFC partners with their respective
          Andromeda DSA codes used for loan processing. This helps advisors
          quickly identify partner banks and product codes.
        </p>

      </div>


      {/* Table */}

      <div className="overflow-x-auto rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900">

        <table className="min-w-[700px] w-full text-xs sm:text-sm md:text-base">

          <thead className="bg-blue-600 text-white sticky top-0">

            <tr>
              <th className="py-2 px-2 sm:px-3 md:px-4 text-left whitespace-nowrap">Serial</th>
              <th className="py-2 px-2 sm:px-3 md:px-4 text-left whitespace-nowrap">Company</th>
              <th className="py-2 px-2 sm:px-3 md:px-4 text-left whitespace-nowrap">Institute</th>
              <th className="py-2 px-2 sm:px-3 md:px-4 text-left whitespace-nowrap">Sub Product</th>
              <th className="py-2 px-2 sm:px-3 md:px-4 text-left whitespace-nowrap">Product</th>
              <th className="py-2 px-2 sm:px-3 md:px-4 text-left whitespace-nowrap">DSA Code</th>
            </tr>

          </thead>


          <tbody>

            {currentRecords.map((item) => (

              <tr
                key={item.serial}
                className="border-b border-gray-100 dark:border-gray-700 hover:bg-blue-50 dark:hover:bg-gray-800 transition-colors duration-150"
              >

                <td className="py-2 px-2 sm:px-3 md:px-4 whitespace-nowrap text-gray-700 dark:text-gray-300">{item.serial}</td>
                <td className="py-2 px-2 sm:px-3 md:px-4 whitespace-nowrap text-gray-700 dark:text-gray-200">{item.company}</td>
                <td className="py-2 px-2 sm:px-3 md:px-4 whitespace-nowrap font-medium text-gray-900 dark:text-white">{item.institute}</td>
                <td className="py-2 px-2 sm:px-3 md:px-4 whitespace-nowrap text-gray-700 dark:text-gray-200">{item.subProduct}</td>
                <td className="py-2 px-2 sm:px-3 md:px-4 whitespace-nowrap text-gray-700 dark:text-gray-200">{item.product}</td>
                <td className="py-2 px-2 sm:px-3 md:px-4 whitespace-nowrap text-blue-600 dark:text-blue-400 font-semibold">
                  {item.dsa}
                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>


      {/* Pagination */}

<div className="flex justify-center items-center gap-1 sm:gap-2 mt-6 flex-wrap text-xs sm:text-sm">

  {/* Previous */}
  <button
    onClick={prevPage}
    disabled={currentPage === 1}
    className="px-3 py-1 sm:px-4 sm:py-2 bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded hover:bg-gray-300 dark:hover:bg-gray-600 disabled:opacity-50 transition-colors"
  >
    Previous
  </button>

  {/* First Page */}
  <button
    onClick={() => setCurrentPage(1)}
    className={`px-3 py-1 sm:px-4 sm:py-2 rounded border transition-colors
      ${
        currentPage === 1
          ? "bg-blue-600 text-white border-blue-600"
          : "bg-white dark:bg-gray-800 dark:text-gray-200 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 border-gray-300"
      }`}
  >
    1
  </button>

  {/* Left dots */}
  {currentPage > 3 && (
    <span className="px-2 text-gray-500 dark:text-gray-400">...</span>
  )}

  {/* Current Page */}
  {currentPage !== 1 && currentPage !== totalPages && (
    <button className="px-3 py-1 sm:px-4 sm:py-2 rounded border bg-blue-600 text-white border-blue-600">
      {currentPage}
    </button>
  )}

  {/* Right dots */}
  {currentPage < totalPages - 2 && (
    <span className="px-2 text-gray-500 dark:text-gray-400">...</span>
  )}

  {/* Last Page */}
  {totalPages > 1 && (
    <button
      onClick={() => setCurrentPage(totalPages)}
      className={`px-3 py-1 sm:px-4 sm:py-2 rounded border transition-colors
        ${
          currentPage === totalPages
            ? "bg-blue-600 text-white border-blue-600"
            : "bg-white dark:bg-gray-800 dark:text-gray-200 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 border-gray-300"
        }`}
    >
      {totalPages}
    </button>
  )}

  {/* Next */}
  <button
    onClick={nextPage}
    disabled={currentPage === totalPages}
    className="px-3 py-1 sm:px-4 sm:py-2 bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded hover:bg-gray-300 dark:hover:bg-gray-600 disabled:opacity-50 transition-colors"
  >
    Next
  </button>

</div>


      {/* Footer */}

      <div className="mt-10 text-sm text-gray-500 dark:text-gray-400">

        <p>
          Source: Andromeda Sales & Distribution Pvt. Ltd., Santacruz (East),
          Mumbai.
        </p>

      </div>

    </div>

  );

};

export default Andro;